# Generated by Django 5.2.1 on 2025-05-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_group_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Адміністратор'), ('user', 'Користувач')], default='user', max_length=20),
        ),
    ]
